const data = [
    {
        
        title: "Ring 'Shiny drop'",
        slug: 'ring-shiny-drop',   
        description: 'The 925 sterling silver ring has a single pear-shaped stone placed slightly above the delicate pavé row and is securely fastened.',
        price: 120,
        category: 'ring',
        img: 'https://static.e-pandora.ua/24258/responsive-images/1698682488___webp_960_960.webp',  
        createdAt: '2024-07-19',
    },
    {
        title: "Ring 'Herbarium'",
        slug: 'ring-herbarium',
        description: 'Ring in 925 silver reflects fresh floral motifs. Three marquise-shaped stones and two pear-shaped stones are the centerpieces.',
        price: 150,
        category: 'ring',
        img: 'https://static.e-pandora.ua/24136/responsive-images/1698416481___webp_960_960.webp',       
        createdAt: '2024-07-19',
    },
    {
        title: "Ring 'Scarlet witch'",
        slug: 'ring-scarlet-witch',
        description: '14k rosegold ring shaped like the Scarlet Witch headdress, has four arrows and is inlaid with a red faux crystal in the middle.',
        price: 130,
        category: 'ring',
        img: 'https://static.e-pandora.ua/23459/responsive-images/1690461423___webp_960_960.webp',    
        createdAt: '2024-02-13',   
    },
    {
        title: "Ring 'Red heart'",
        slug: 'ring-red-heart',  
        description: "The centerpiece is a heart-shaped artificial red crystal that rises above the ring's surface, which is inlaid with sparkling pavé.",
        price: 150,
        category: 'ring',
        img: 'https://static.e-pandora.ua/22411/responsive-images/1673445032___webp_960_960.webp',       
        createdAt: '2020-07-19',
    },
    {
        title: "Ring 'Wish'",
        slug: 'ring-wish', 
        description: "925 sterling silver plated in 14k rose gold is encrusted with a row of pavé stones, following the curve of a forked knuckle.",
        price: 170,
        category: 'ring',
        img: "https://static.e-pandora.ua/21861/responsive-images/1667385773___webp_960_960.webp",       
        createdAt: '2023-07-19',
    },
    {
        title: "Bracelet 'Shiny plates'",
        slug: 'bracelet-shiny-plates',
        description: "This 925 sterling silver bracelet features a series of triangular plates separated by eight brilliant cubic zirconia stones.",
        price: 220,
        category: 'bracelet',
        img: 'https://static.e-pandora.ua/24091/responsive-images/1698309116___webp_960_960.webp',       
        createdAt: '2024-12-23',
    },
    {
        title: "Bracelet 'Shiny drop'",
        slug: 'bracelet-shiny-drop',
        description: "The bracelet has a pear-cut cubic zirconia stone in the middle, which is slightly raised above the delicate pavé path.",
        price: 200,
        category: 'bracelet',
        img: 'https://static.e-pandora.ua/24083/responsive-images/1698307799___webp_960_960.webp',       
        createdAt: '2024-03-19',
    },
    {
        title: "Bracelet 'Red heart'",
        slug: 'bracelet-red-heart',  
        description: "The  artificial red heart-shaped crystal accent is partnered with a row of sparkling cubic zirconia stones.",
        price: 180,
        category: 'bracelet',
        img: 'https://static.e-pandora.ua/24075/responsive-images/1698306950___webp_960_960.webp',      
        createdAt: '2024-07-16', 
    },
    {
        title: "Bracelet 'Herbarium'",
        slug: 'bracelet-herbarium',
        description: "This silver jewelry, reminiscent of dried flowers and leaves, is inlaid with marquise- and pear-shaped cubic zirconia.",
        price: 180,
        category: 'bracelet',
        img: 'https://static.e-pandora.ua/22742/responsive-images/1677077696___webp_960_960.webp',       
        createdAt: '2024-11-19',
    },
    {
        title: "Necklace 'Shiny drop'",
        slug: 'necklace-shiny-drop',
        description: "This 925 sterling silver necklace has a pear-shaped cubic zirconia stone as its main element.",
        price: 230,
        category: 'necklace',
        img: 'https://static.e-pandora.ua/24212/responsive-images/1698675335___webp_960_960.webp',       
        createdAt: '2022-07-19',
    },
    {
        title: "Necklace 'Captain Marvel'",
        slug: 'necklace-captain-marvel', 
        description: "The 14k gold-plated necklace features an eight-pointed star with a row of pavé. It is engraved with the inscription 'HIGHER FURTHER FASTER'",
        price: 340,
        category: 'necklace',
        img: 'https://static.e-pandora.ua/23510/responsive-images/1691053766___webp_960_960.webp',       
        createdAt: '2024-07-24',
    },
    {
        title: "Earrings 'Captain Marvel'",
        slug: 'earrings-captain-marvel',
        description: "14k gold-plated earrings are characterized by a modern graphic design. The meteor's tail is inlaid with a row of pavé.",
        price: 150,
        category: 'earrings',
        img: 'https://static.e-pandora.ua/21779/responsive-images/1667334277___webp_960_960.webp',       
        createdAt: '2024-12-19',
    }
]

export default data;